[package]
name = "bolha"
version = "0.1.0"
license = "CC-BY-NC-SA-4.0"
authors = ["Tony Lazenka <tlazenka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
